# GENERATED FILE. Use with Kubernetes 1.9+
# TO UPDATE, modify files in install/kubernetes/templates and run install/updateVersion.sh
apiVersion: v1
kind: Service
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    istio: sidecar-injector
spec:
  ports:
  - name: https-webhook # optional
    port: 443
  selector:
    istio: sidecar-injector
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-sidecar-injector-service-account
  namespace: istio-system
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: istio-sidecar-injector
  namespace: istio-system
  labels:
    istio: sidecar-injector
spec:
  replicas: 1
  template:
    metadata:
      name: istio-sidecar-injector
      labels:
        istio: sidecar-injector
    spec:
      serviceAccountName: istio-sidecar-injector-service-account
      containers:
        - name: webhook
          image: docker.io/istio/sidecar_injector:0.6.0
          imagePullPolicy: IfNotPresent
          args:
            - --tlsCertFile=/etc/istio/certs/cert.pem
            - --tlsKeyFile=/etc/istio/certs/key.pem
            - --injectConfig=/etc/istio/inject/config
            - --meshConfig=/etc/istio/config/mesh
            - --healthCheckInterval=2s
            - --healthCheckFile=/health
          volumeMounts:
          - name: config-volume
            mountPath: /etc/istio/config
            readOnly: true
          - name: certs
            mountPath: /etc/istio/certs
            readOnly: true
          - name: inject-config
            mountPath: /etc/istio/inject
            readOnly: true
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=2s
            initialDelaySeconds: 4
            periodSeconds: 4
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/sidecar-injector
                - probe
                - --probe-path=/health
                - --interval=2s
            initialDelaySeconds: 4
            periodSeconds: 4
      volumes:
      - name: config-volume
        configMap:
          name: istio
      - name: certs
        secret:
          secretName: sidecar-injector-certs
      - name: inject-config
        configMap:
          name: istio-inject
          items:
          - key: config
            path: config
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: istio-sidecar-injector
webhooks:
  - name: sidecar-injector.istio.io
    clientConfig:
      service:
        name: istio-sidecar-injector
        namespace: istio-system
        path: "/inject"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lRTUxwSXBaZldNWjJoUWxhQXlDZUtSakFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNVlUUmhOemRrWWkweU5qZzVMVFJtTldZdFltWTFZeTA0WWpNek5tVXdNV014TkdVdwpIaGNOTVRnd05UTXdNVEl4T0RFM1doY05Nak13TlRJNU1UTXhPREUzV2pBdk1TMHdLd1lEVlFRREV5UTVZVFJoCk56ZGtZaTB5TmpnNUxUUm1OV1l0WW1ZMVl5MDRZak16Tm1Vd01XTXhOR1V3Z2dFaU1BMEdDU3FHU0liM0RRRUIKQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNPblpFakpmc2FQVlRuOEtMNDg2Q3Z1NENTTExnNHVyOWkwZ00zcVF4QwpTTWVSVVVoMytpaUlQbjRVRVdObElLWlF3TTY4NmxqOHllNlovU3BJMDF5QWFPaTFDUThEYk1WZEhxM3NFMTBXClVKZWZ4YjJtRjE1aGpIMlMrQmhybkR5STdnVlNoL0NNcnFQQ0gvQUVwSjkvL3pHWE8yM2p3ZjFrTkl5TUVQYW4KMFNCL2M0bHMrSUdxOEEzV1NyTG1VNFlxNHZ0dzJVSXpWcXVrSE1tZERRcEoyM3kyRnRIVHpEZDk3am03MVZoLwowdEVmNTM0SXpxalc3cTBkbGhOTzdST1RGbkpNdlhoTkNBYkU3cUNQOUYwam1DUGtKWVgwMEsxWHZCUDA1cnBaCkFHMEs1TFdzQWNrd0RsY0gxeHdyS1ZHTTZhcERSQnlEemdYM0ZYaVRScmNSQWdNQkFBR2pJekFoTUE0R0ExVWQKRHdFQi93UUVBd0lDQkRBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBbwo5Nm5RSHp1NC9nL3dkT3B2ODhUYVJEQnpDN2V1TjJUOVB1eTFqa09ZUC9EbmNoM2lhOWZ3RWhld2NqWUFkbDVKCjZSTUhqTzRhNFlFbzU5WXA5djZ5eUc2bHZsbDc5RHB6SmVOc1VyakhmY2VldGRobnBHS1h1N0pvYnprV2Y0M2IKNTNpRkxhWFkrVVM3YStwM3JXdk1BZXZuc3lNUkNiK2JKYmZ4MFVWQTFnTnVrRXRWLzRHcS9zMndmZUhSdk02RQpPaXU3U1BHMXFMV2prR0c1WDlHT01tUFFKUGRtS0ZkRllmKzMrZ3hWT0J6bXI0VUdBY05UR2lieFlwaXhleFM2Ckhod2ZON0xKYVUxUjRHVU1PQ3RkYTVqQjNTVDBYYWlKbWZtRVZDMWtMWVFFVjA5T2E5ci8wZnNvUkJsUC9KeTcKeXVxc3NaVkh3MlU5M3EyNElmY0YKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        istio-injection: enabled
---
